bookworm:
  stage: build
  tags: [ docker ]
  image: debian:bookworm
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install devscripts build-essential lintian debhelper libssl-dev
    - ./debian/make_users.sh
    - dpkg-buildpackage --no-sign
    - mv ../*.deb .
  artifacts:
    paths:
      - ./*.deb

bullseye:
  stage: build
  tags: [ docker ]
  image: debian:bullseye
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install devscripts build-essential lintian debhelper libssl-dev
    - ./debian/make_users.sh
    - dpkg-buildpackage --no-sign
    - mv ../*.deb .
  artifacts:
    paths:
      - ./*.deb

buster:
  stage: build
  tags: [ docker ]
  image: debian:buster
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update
    # Buster was the only Debian release that included the qmail-uids-gids package
    - DEBIAN_FRONTEND=noninteractive apt-get -y install devscripts build-essential lintian debhelper libssl-dev qmail-uids-gids
    - dpkg-buildpackage --no-sign
    - mv ../*.deb .
  artifacts:
    paths:
      - ./*.deb

focal:
  stage: build
  tags: [ docker ]
  image:
    name: ubuntu:focal
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update
    # Focal was the only Ubuntu release that included the qmail-uids-gids package
    - DEBIAN_FRONTEND=noninteractive apt-get -y install devscripts build-essential lintian qmail-uids-gids debhelper libssl-dev
    - dpkg-buildpackage --no-sign
    - mv ../*.deb .
  artifacts:
    paths:
      - ./*.deb

jammy:
  stage: build
  tags: [ docker ]
  image:
    name: ubuntu:jammy
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install devscripts build-essential lintian debhelper libssl-dev
    - ./debian/make_users.sh
    - dpkg-buildpackage --no-sign
    - mv ../*.deb .
  artifacts:
    paths:
      - ./*.deb

kinetic:
  stage: build
  tags: [ docker ]
  image:
    name: ubuntu:kinetic
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install devscripts build-essential lintian debhelper libssl-dev
    - ./debian/make_users.sh
    - dpkg-buildpackage --no-sign
    - mv ../*.deb .
  artifacts:
    paths:
      - ./*.deb

lunar:
  stage: build
  tags: [ docker ]
  image:
    name: ubuntu:lunar
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install devscripts build-essential lintian debhelper libssl-dev
    - ./debian/make_users.sh
    - dpkg-buildpackage --no-sign
    - mv ../*.deb .
  artifacts:
    paths:
      - ./*.deb
